#!/bin/bash

export CONSUMER_KEY=SjepS24yzEOyyxAsboQopOhI8
export CONSUMER_SECRET=PIrnZjVnFfVFqnz0ItzL8lPtdeAzrQAZnVjtFRYZGP0tKtfvEl
export ACCESS_TOKEN_KEY=26008755-1ceBuzVNXrY9qN2vmxT6o3fXePfV6GHO39zeT74SJ
export ACCESS_TOKEN_SECRET=LqJ2tLcUl8AAfm45EFPzPF668BJyXnaeYXC4RWfzzUwEn

echo "environment variables sourced..."